name: battleroyal2
version: '25.7.4'
main: seml.battleroyal2.Battleroyal2
api-version: '1.21'

commands:
  battleroyal:
    description: 배틀로얄 시작
    usage: /battleroyal <start>
  changenick:
    description: 플레이어 닉네임 변경
    usage: /changenick <newNick|reset>
  makeSpawn:
    description: 대기실 생성
    usage: /makeSpawn
  addTeam:
    description: 플레이어를 구독자 팀에 추가
    usage: /addSubTeam <subTeam|memTeam>> <playerName>