name: battleroyal2
version: '1.0-SNAPSHOT'
main: seml.battleroyal2.Battleroyal2
api-version: '1.21'

commands:
  battleroyal:
    description: 배틀로얄 시작
    usage: /battleroyal [start]
  changenick:
    description: 플레이어 닉네임 변경
    usage: /changenick [new_nick|reset]